### ISSUE TITLE
PvP Npcs in Stormwind overlap eachother

### ISSUE THREAD

**Issue by leahnie956** [SunwellWoW/Sunwell-TBC-Bugtracker#106]
Decription: 
PvP Npcs in Stormwind overlap each other

How it works: 
shouldnt over lap

How it should work: 
shouldnt over lap

Source (you should point out proofs of your report, please give us some source): 
![ethr](https://user-images.githubusercontent.com/25886407/44006211-dc3fd144-9e45-11e8-9cba-1ca15ddb71b3.jpg)

**Comment by Dootz** [comment]
fixed

**Comment by Nadiirr** [comment]
This problem came back. 
![screenshot_141](https://user-images.githubusercontent.com/36300104/49268767-3de9f200-f416-11e8-9bf7-d4e0ac858496.png)
