### ISSUE TITLE
[PvE][Dungeon]Mechanar

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#1797]
Decription: 4 issues we found while running Mechanar earlier today:

How it works:

1) Sunseeker Netherbinder's adds don't despawn when the caster is killed.

2) Sunseeker engineer not linked to demon group (next to the stairs before first boss) 

3) Sunseeker Astromage fire shield (magic buff) not dispellable (we had shield slam, purge, spellsteal) 

4) Nethermancer Sepethrea's fire elementals run at x10 speed (this is fixed but not applied afaik)

How it should work: 
1) When the caster is killed, summoned adds should despawn.

2) Sunseeker is part of the group and should be pulled when the group is.
https://gyazo.com/964ac960b8f7f4f13e7443c4e05042e2 This is where the group was.
3) Fire shield should be dispellable.

4) Elementals should run at player base speed.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
~3rd point is fixed but not implemented yet as well.

**Comment by codey07** [comment]
4th point must not be implemented yet

**Comment by zkillertheman** [comment]
This is not fixed, "Nethermancer Sepethrea's fire elementals run at x10 speed" is still the same, also. you should be able to do the gauntlet after Nethermancer Sepethrea without killing her, currently if you walk down the path no mobs spawn.

**Comment by NeonicSupersonic** [comment]
There also seems to be combat bug related to nethermancer boss. Basically, after engaging any trash combat stays forever and only way to drop it is to relog. And it kept happening to my group, we were forced to relog after every 3 packs to be able to drink. However, after we killed nethermancer, it never happened again. Strangely, day before that we didnt have any issues with combat in this dungeon. Also heroic difficulty, if that means anything.
