### ISSUE TITLE
[Profression][Herbalism]Herbs don't seem to be respawning

### ISSUE THREAD

**Issue by bigripper** [SunwellWoW/Sunwell-TBC-Bugtracker#1993]
Description: I just went around Elwynn Forest and pick every Silver Leaf, Peacebloom, and Earthroot. I did a few more loops to get the skill up more and NOTHING was re-spawned. Gave it a few minutes, still nothing. 30 minutes later I went back to the original spawn and it still wasn't there. I then did another loop and still no herbs spawned.

No one else was in the zone by the way.

How it works:  Herbs in Elwynn don't seem to be re spawning

How it should work: I'm not sure the respawn rate, but never experienced this on a server before.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_112718_223018](https://user-images.githubusercontent.com/45222160/49131207-8bd6ec80-f294-11e8-8b4f-2ab04d168c6e.jpg)

notice the 31 min in the right hand. only way i knew to show "proof"

**Comment by bigripper** [comment]
Just went back in. Almost 1 hour later, still nothing in Elwynn.

**Comment by Wojtyas** [comment]
Hi there pal, we have implemented such thing like HerbPool which prevents resping herb in same place it was. It will respawn somewhere on same map (in your case it's Elwynn Forest) after 5 minutes but not in same place. It works like that in entire world.

**Comment by bigripper** [comment]
I think you missed the part where even after 30 minutes, nothing was respawned in elwynn

**Comment by Tundra28** [comment]
Low spawn rates on all Azuremist isle and Bloodwatch Isle! Plz fix HERB SPAWN RATES!
