### ISSUE TITLE
Warlock Talent: Demonic Knowledge

### ISSUE THREAD

**Issue by Ocaliehpo** [SunwellWoW/Sunwell-TBC-Bugtracker#2288]
Description: 
The talent does nothing

How it works: 
The talent does nothing

How it should work: 
The warlock should gain spell power depending of the stats of the pet

Source (you should point out proofs of your report, please give us some source): 
Summon any pet and look at the spellpower stats, they don't change

**Comment by Sabre142** [comment]
Should be high priority in my opinion. Breaks the demonology spec.

**Comment by Ocaliehpo** [comment]
It worked for a moment yesterday if I'm not wrong, but after a crash the talent stopped to work again

**Comment by GeorgieTragnar** [comment]
still not working, this is pretty huge talent fix it, the buff is not at all applied when talented and demon is out

**Comment by Darakai** [comment]
You get the buff 1 out of 20 times, this is a realy big Talent wich should be fixed fast.

**Comment by Espranty** [comment]
Still not working , just specced demonology and it doesnt work . Prio this please !

**Comment by Mirlmunir** [comment]
Fix that talent guys please, it's really annoying to get the buff 1/40 out of time....

**Comment by Kanibar** [comment]
This talent is semi bugged, the you will recive the buff after standing still for like 30sec after a fight, and loose it once you mount (intended) there seem too be something wrong with the triggering off the talent

**Comment by Lunasoll** [comment]
Fix it please. It's still not working

**Comment by GeorgieTragnar** [comment]
I noticed that some buffs overwrite this buff (mark of the wild/gift of the wild did that for me)

**Comment by GeorgieTragnar** [comment]
your rewriting of the buff system must have broken this talent...

**Comment by brobrobro187** [comment]
still not working

**Comment by jockeboschko** [comment]
Its up most of the time right now but it does not update on stat changes on pet from buffs and the like

**Comment by SunwellTracker** [comment]
Talent fixed. The fix will be implemented tomorrow morning.
