### ISSUE TITLE
City of Light quest doesn't complete

### ISSUE THREAD

**Issue by 123abcppp** [SunwellWoW/Sunwell-TBC-Bugtracker#2708]
City of Light quest despawns at the same point every time about 12minutes into the escort with no credit given. 
footage: https://streamable.com/3p3jg
I have not found a way to complete quest.

**Comment by tyk0s** [comment]
Same happened to me just now.

**Comment by renen9** [comment]
Not sure if he should be attackable by mobs spawned from quests down in lower city but he just died down there for me.

**Comment by tyk0s** [comment]
Is this live? if so it still doesnt work,

**Comment by Dootz** [comment]
should be fixed now. Could you verify @Wojtyas  or @Piootrek  ?

**Comment by neheri** [comment]
Still doesn't work, 4 elementals in a row disappeared in the between aldor and scryers.

**Comment by Dootz** [comment]
yeah, unfortunately, I've made a mistake and it wasn't updated yet. We'll verify it after update. I'm sorry.

**Comment by 0vertime** [comment]
It completes the quest around the tour of scryers tier, but it still despawns afterwards early without finishing the whole RP.

**Comment by Dootz** [comment]
yes i'm aware of it. it was just a temporary fix. After investigation i found what was causing this issue and it'll be finally resolved with next server update.
