### ISSUE TITLE
[Quest][NPC] Frostmaw

### ISSUE THREAD

**Issue by Merulifox** [SunwellWoW/Sunwell-TBC-Bugtracker#2732]
Quest shows as completed in log. Unable to turn in. Fresh Carcass item was still in inventory when looting Frostmaw due to party member activating encounter. Perhaps both can not be in inventory at the same time?

**Comment by 0vertime** [comment]
This can happen if you place it in bank, abandoning and re-taking should fix it.

**Comment by Merulifox** [comment]
It did not fix it. Item still shows as Fresh Carcass. Still unable to turn in.
