### ISSUE TITLE
Shy Rotam

### ISSUE THREAD

**Issue by Alucard1986** [SunwellWoW/Sunwell-TBC-Bugtracker#2849]
Description: Bugged quest turn in

How it works: I cant turn in quest after i killed shy rotam

How it should work: well it should work like that so if i killed him i can trun it in....

Source (you should point out proofs of your report, please give us some source):

**Comment by 0vertime** [comment]
Worked for me. Sure you killed the right cat?

**Comment by Alucard1986** [comment]
we killed both. 100% sure.

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.

**Comment by sinfer** [comment]
not fixed for me atleast. any help?
![wowscrnshot_121418_124643](https://user-images.githubusercontent.com/45524181/49999051-7f45da00-ff9e-11e8-8528-4060f46e3755.jpg)
