### ISSUE TITLE
[Zone] Zangarmarsh 

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#288]
- [x]  All mobs in the zone have a tendency to glitch through the ground, specially when walking through water.

- [x] Boglash (GUID 65572, entry 18281) Is not patrolling.

- [x] Boglash (entry 18281)missing immunity masks. Should be immune to all slow, snare and poison effects.
https://www.wowhead.com/npc=18281/boglash#comments

- [x] Fen Striders (entry 18134)and Marsh Walkers (entry 18135) aren't patrolling. Note: they should only patrol in water.
GUID Fen Striders that I could find:

64767
64768
64769
64770
64771
64772
64773
64774
64775
64776
64777
64778
64779
64780
?
64782
64783
64784
64785
64786
64787
?
64789
64790
64791
64792
64793
?
64795
64796
64797
64798
64799
?
64801
64802
64803
64804
64805
64806
64807
64808
64809
64810
64811
64812
64813
64814
64815
64816
64817
64818

Marsh Walker GUID:

64819
64820
64821
64822
64823
64824
64825
64826
64827
64828
64829
64830
64831
64832
64833
64834
64835
64836
64837
?
64840

https://www.wowhead.com/npc=18134/fen-strider
https://www.wowhead.com/npc=18135/marsh-walker

- [x] Umbrafen Eel (entry 18138) missing ability Electric Skin http://db.hellfire-tbc.com/?spell=35319 (buff) triggering this: http://db.hellfire-tbc.com/?spell=35320 for around 20 damage. 
https://www.wowhead.com/npc=18138/umbrafen-eel#comments

- [x] Escort NPC Keyra Longmane (entry 17969) missing abilities Moonfire https://www.wowhead.com/spell=31401/moonfire and Wrath https://www.wowhead.com/spell=9739/wrath
https://www.wowhead.com/npc=17969/kayra-longmane#abilities

- [x] Keyra Longmane (entry 17969) missing ability Healing Touch (should be cast on both her and the players with the quest)
>This quest is really too easy, i had 5 mobs attacking me, started quest quickly, and she healed me 2600 each heal. You just can't fail this.
https://www.wowhead.com/quest=9752/escape-from-umbrafen#comments:id=95855

- [ ] Kayra Longmane (GUID 63625, entry 17471) glitching through ground, sometimes weird pathing.

- [ ] Escape from Umbrafen (quest ID 9752) completed even if you let the NPC die and quest marked as "Failed".
https://www.wowhead.com/quest=9752/escape-from-umbrafen

- [x] Umbrafen Witchdoctor (entry 20115) missing spawn in the middle floor of the building at these cords: ![Image](https://i.gyazo.com/1c29862e5f11a557dab909a475de0a14.png)
"...one Umbrafen Witchdoctor had indeed respawned on each of the floors in the building..."
https://www.wowhead.com/npc=20115/umbrafen-witchdoctor#comments:id=194964

- [x] Umbrafen Witchdoctor (entry 20115) missing ability Terror Totem http://db.hellfire-tbc.com/?spell=35197
https://youtu.be/E2K5d0KCZmI?t=51s
https://youtu.be/E2K5d0KCZmI?t=2m43s

- [x] Umbrafen Witchdoctor (entry 20115) AI issues, currently spams 1 ability either the buff or Shrink. Should not cast shrink unless it's dispelled or fades and they should not rebuff themselves as long as they still have the buff.

- [x] Blacksting (entry 18283) missing ability Fatal Sting.
https://www.wowhead.com/spell=17170/fatal-sting
https://www.wowhead.com/npc=18283/blacksting#abilities

- [x] Rajah Haghazad (GUID 84370, entry 18046) missing abilities; cleave, mortal strike.
https://www.wowhead.com/npc=18046/rajah-haghazed#abilities

- [x] Rajah Haghazad (GUID 84370, entry 18046) appears to be changing weapon mid combat to a polearm?
https://youtu.be/XXccGIzZ0Dw?t=48s

- [x] Rajah Haghazad (GUID 84370, entry 18046) is too accessable.
Sunwell: ![Image](https://i.gyazo.com/801bb2b3a8b47662264db0c997f9f2e4.jpg)
Retail: ![Image](https://i.gyazo.com/5bd28a83983293f672b8cd69d536220c.png)
Sunwell: ![Image](https://i.gyazo.com/6bf899cecd214aa0a895a655b03f7d20.jpg)
Retail: ![Image](https://i.gyazo.com/b9b85bb1dd9f6e1af9cf2e9b81d743b2.jpg)
No mobs blocking your path to him. Add 2 Darkcrest Taskmasters (entry 18086) in front of the building, 1 Darkcrest Taskmaster (entry 18086) in the stone tent thing to the left. 2 Dreghood Drudge (entry 18122) by the mushrooms. 1 Darkcrest Taskmaster (entry 18086) patrolling along the water. 1 Dreghood Drudge (entry 18122) to join his friend to the right in this screenshot: ![Image](https://i.gyazo.com/57d02cdb3098e660d26f1f8070fb33c0.jpg)
Red=Taskmaster, yellow=slave
The mobs can be seen in this screenshot: ![Image](https://i.gyazo.com/b9b85bb1dd9f6e1af9cf2e9b81d743b2.jpg)

- [x] Darkcrest Taskmaster's (entry 18086) "Curse of Nazjatar" (ID 34812) should last 8 seconds, currently lasts 4. 
http://db.hellfire-tbc.com/?spell=34812
https://www.wowhead.com/spell=34812/curse-of-nazjatar

- [ ]  Bloodscale Slavedriver (18089), Darkcrest Slaver(19946) and Bloodscale Overseer(20088) should call a Dreghood Drudge (only one) to assist them when engaged, slave will despawn if when the master is killed if no damage was done to the slave. Could not find info if Darkcrest Taskmaster (18086) behaves in the same way but it makes sense.
https://www.wowhead.com/npc=18089/bloodscale-slavedriver#comments:id=247100
https://www.wowhead.com/npc=20088/bloodscale-overseer#comments:id=148094
https://www.wowhead.com/npc=19946/darkcrest-slaver#comments:id=352039
https://www.wowhead.com/npc=18086/darkcrest-taskmaster

Video of slave being pulled: https://youtu.be/4TuiresbFSU?t=1m53s

- [ ] Bloodscale Slavedriver (18089), Darkcrest Slaver(19946) and Bloodscale Overseer(20088) does not attempt to flee when on low health, they should do so unless they have a slave assisting them. Again... No info about Darkcrest Taskmaster (18086) behaviour.
https://www.wowhead.com/npc=19946/darkcrest-slaver#comments:id=352039

- [x] Darkcrest Siren (entry 18087) missing AI, should run away after using Frost Nova.

- [ ] Dreghood Drudge (entry 18122)+Wrekt Slave(entry 18123) does not run away when you kill a Taskmaster/Overseer/Slavedriver/Slaver next to it. 
https://www.wowhead.com/npc=18089/bloodscale-slavedriver#comments:id=261460
https://www.wowhead.com/npc=20088/bloodscale-overseer#comments:id=148094
https://www.wowhead.com/npc=19946/darkcrest-slaver#comments
https://www.wowhead.com/npc=18086/darkcrest-taskmaster

- [x] Dreghood Drudge (entry 18122) and Wrekt Slave (entry 18123)  missing abilities: Shared Bonds (Should only be cast on other slaves)
http://db.hellfire-tbc.com/?spell=34788
http://db.hellfire-tbc.com/?spell=34789
https://www.wowhead.com/npc=18122/dreghood-drudge#abilities
https://www.wowhead.com/npc=19946/darkcrest-slaver#comments:id=352039

Shared Bonds being used: https://youtu.be/c-VoYkESb-U?t=13s

- [ ] Darkcrest Sentry (entry 20079) should call for assistance from nearby nagas on low health and doing an emote while doing it.
-Aggro emote: You are spotted by the Bloodscale Sentry!
-Call for help emote: Bloodscale Sentry calls for help!
https://www.wowhead.com/npc=20079/darkcrest-sentry#comments
https://github.com/dalaranwow/dalaran-wow/issues/4478

- [x] Darkcrest Sentry (entry 20079) and Bloodscale Sentry (entry 20090) should be patrolling in the shallow water in the Naga areas.

- [x] Bloodscale Elemental (entry 20792) spawns in game, should only be summoned by Rajis Fyashe (entry 18044). They are supposed to be https://www.wowhead.com/npc=20090/bloodscale-sentry which sound call friendly nagas to assist them like the Darkcrest Sentry.
https://www.wow-freakz.com/npc_finder.php?npc=20792&name=bloodscale-elemental
https://wow.gamepedia.com/Bloodscale_Elemental

- [x] Rajis Fyashe (entry 18044) missing ability Mass Elementals: https://www.wowhead.com/spell=35594/mass-elementals  
Broken ability: https://www.wowhead.com/spell=34787/freezing-circle, she begins to cast it but nothing happens. 
Water Sprout does no damage, supposed to be 450-550 https://www.wowhead.com/npc=18044/rajis-fyashe#comments:id=394368
https://www.wowhead.com/spell=35499/water-spout

- [ ] As the Crow Flies (quest 9718) missing whispers from Ysiel Windsinger when flying as crow form. 
(Flight starts)

34 seconds in: It's just like the structure you described at Umbrafen Lake. Does this mean the naga are pumping water out of all the lakes in Zangarmarsh?

56 seconds: The naga are even pumping the water out of their own lake! What purpose could that possibly serve?

83 seconds: There! Those pipes all appear to be connected to that structure. It can't possibly fit all the water they've been stealing. Where are they keeping it?

143 seconds: What we saw explains what happened in the Dead Mire. There was a lake here once. If we don't stop the naga, all of the marsh will soon look like this!  (quest completes)

155 seconds flight ends.

Flight on sunwell is only 146 seconds, either flying too fast or wrong route.

http://wowwiki.wikia.com/wiki/Quest%3AAs_the_Crow_Flies
https://www.youtube.com/watch?v=hJwiw9qx_lU

- [x] All Sporebats in the zone should give "Energizing Spores" upon death (works on Sporewing but no one else, entry 18280). http://db.hellfire-tbc.com/?spell=35336
https://www.wowhead.com/npc=18129/greater-sporebat#comments
https://www.wowhead.com/npc=18128/sporebat#comments
https://www.wowhead.com/npc=20387/young-sporebat#comments
https://github.com/Looking4Group/L4G_Core/issues/2199

- [x] Scout Jyoba(18035) should be lying down, dead. Currently walking around.
https://www.wowhead.com/npc=18035/scout-jyoba#comments
https://youtu.be/GtHKdP1Y2HA?t=46s

 - [x] Marsh Dredger (18137)+ Marsh Lurker(18136) not always fighting with nearby Sporeloks
https://www.wowhead.com/npc=18137/marsh-dredger
https://www.wowhead.com/npc=18136/marsh-lurker

- [x] Steam Pump Overseer (entry 18340) missing abilities: Knockdown, Toughen
https://www.wowhead.com/npc=18340/steam-pump-overseer#abilities

- [x] Ironvine Seeds http://db.hellfire-tbc.com/?item=24355 for quest http://db.hellfire-tbc.com/?quest=9720 cannot be used at the steam pump. "You have no target" error message. Unsure if it spawns an Overseer when used, needs testing when quest works. https://www.wowhead.com/npc=18340/steam-pump-overseer#comments:id=16538

Umbrafen Lake Overseer spawning: https://youtu.be/YUutHisDI0Y?t=55s Says:  "I will show you not to cross us again!"
Lagoon Overseer spawning: https://youtu.be/YUutHisDI0Y?t=1m49s Says: "I will make you pay for that!"
Serpent Lake Overseer spawning: https://youtu.be/YUutHisDI0Y?t=2m36s Says:  "I will show you not to cross us again!"

- [x] Keleth (entry 17901) missing speech bubble on mouse over https://www.wowhead.com/npc=17901/keleth

- [x] Feralfen Druid (entry 20270) does not attempt to heal (should have regrowth). "Roc form" (ID 35200) states that 'armor and hit points increased'.
https://www.wowhead.com/spell=35200/roc-form
https://www.wowhead.com/npc=20270/feralfen-druid#abilities

- [ ] Feralfen Druid (entry 20270) Roc Form should actually be a bird, not a bear. Seen in this video: https://www.youtube.com/watch?v=hAoN2OH2Fn0&feature=youtu.be&t=236

- [x] Feralfen Hunter (entry 18113) does not use his net ability. They all have 2 pets summoned, looks like these aren't actual pets but spawned mobs close to him.
![Image](https://i.gyazo.com/91c0d71261b9d585e6ee63b0650936c5.png) You can aggro the sporebats individually without aggroing the hunter. He is using ability https://www.wowhead.com/spell=32060/summon-sporebat to summon https://www.wowhead.com/npc=18201/tamed-sporebat but for some reason it doesn't count as hit pet properly.
https://www.wowhead.com/npc=18113/feralfen-hunter#abilities

- [ ] All Marshfang mobs with mana drain should spawn with 0 mana and drain their way up when someone engages them. They should use their respective abilities when they have enough mana for it. Currently they drain rogues, warriors or druids in bear/cat form, they shouldn't attempt this.
https://www.wowhead.com/npc=18131/marshfang-slicer
https://www.wowhead.com/npc=18285/count-ungula
https://www.wowhead.com/npc=20196/bloodthirsty-marshfang
Ripper:
https://youtu.be/hBOjPHXsj6c?t=13s
Count ungula:
https://youtu.be/GqvshZ9ztLc?t=5s
https://www.wowhead.com/npc=18130/marshfang-ripper
Marshfang Slicer: 
https://youtu.be/bzLYStDy7rA?t=31s

- [x] Marshfang Ripper (entry 18130) missing ability Arcane Explosion: https://www.wowhead.com/spell=33860/arcane-explosion
https://www.wowhead.com/npc=18130/marshfang-ripper#abilities

- [x] Marshfang Slicer (entry 18131) missing ability Nether Shock https://www.wowhead.com/spell=35334/nether-shock. 
https://www.wowhead.com/npc=18131/marshfang-slicer#comments:id=57143:reply=5066

- [ ] Marshrock Threshalisk (entry 19706),Ragestone Threshalisk (entry 20279), Ragestone Trampler (entry 20280), Ironspine Gazer (entry 19730), Ironspine Threshalisk (entry 19729) missing ability Feign Death? According to wowhead they should feign death like a hunter and then charge you. Their charge ability is broken, does not charge the player and it stuns themselves for some reason.
Emote after Feign Death: "Ragestone Trampler stops playing dead and charges forward!"

https://www.wowhead.com/npc=19706/marshrock-threshalisk#comments:id=32204
https://www.wowhead.com/npc=20279/ragestone-threshalisk#comments
https://www.wowhead.com/npc=20280/ragestone-trampler#comments:id=332101
https://www.wowhead.com/npc=19730/ironspine-gazer#comments:id=298794
https://www.wowhead.com/npc=19729/ironspine-threshalisk#comments:id=855497

I assume Marshrock Stomper (entry 20283) should also have this ability, could not find any info about it though. Otherwise it would be the only Basilisk in Zangarmarsh without this ability.

**edit:** found the spell http://db.hellfire-tbc.com/?spell=19822

- [x] Marshrock Stomper (entry 20283) missing ability: Stomp https://www.wowhead.com/spell=12612/stomp
https://www.wowhead.com/npc=20283/marshrock-stomper#abilities

- [ ] Fungal Giant (entry 19734) and Bog Lord (entry 18127) missing ability ??? not sure what the ability is called, works similarly to Hungerfen in underbog. He'll do an emote and spawn a mushroom on the player that will grow and explode.
https://www.wowhead.com/npc=19734/fungal-giant#comments:id=99506
https://www.wowhead.com/spell=35273/unstable-mushroom-primer
https://www.wowhead.com/spells?notFound=35256
http://db.hellfire-tbc.com/?spell=35273
http://db.hellfire-tbc.com/?spell=35256
https://www.wowhead.com/npc=18127/bog-lord#comments:id=152688

- [x] Starving Fungal Giant (entry 18125) and Starving Bog Lord (entry 19519) ability https://www.wowhead.com/spell=35244/choking-vines does not become https://www.wowhead.com/spell=35247/choking-wound at 5 stacks.
https://www.wowhead.com/npc=18125/starving-fungal-giant
https://www.wowhead.com/npc=19519/starving-bog-lord

- [x] Withered Bog Lord (GUID 69278, entry 19402) spawned inside object
![Image](https://i.gyazo.com/811089c881a2f81e1f166b386702c675.png) 

- [ ] Missing event: now and then Starving Fungal Giants (entry 18125) and Starving Bog Lords (entry 19519) will start to migrate east to find food, as seen in this video:
https://www.youtube.com/watch?v=ESGg3NwOmfw

- [x] Bloodscale Enchantress (entry 18088) ability Freezing circle is broken. Same as Rajis Fyashe (entry 18044). 
https://www.wowhead.com/npc=18088/bloodscale-enchantress#comments:id=247099
https://www.wowhead.com/spell=34787/freezing-circle#comments:id=248879
https://www.wowhead.com/spell=34787/freezing-circle
http://wowwiki.wikia.com/wiki/Bloodscale_Enchantress

- [x] Bloodscale Enchantress (entry 18088) uses wrong version of Arcane Missiles, the one she uses is instant and does 116 damage. It should be a 5 second channeled spell doing 140 to 210 damage per tick. (can't find proper spell ID, could be one of these 2: http://db.hellfire-tbc.com/?spell=33988 or http://db.hellfire-tbc.com/?spell=22272 ?)

- [x] Captain Krosh (entry 18992) missing ability Furious Rage (ID 35491) which should trigger Exhaustion (ID 35492).
https://www.wowhead.com/spell=35492/exhaustion
http://db.hellfire-tbc.com/?spell=35491
https://www.wowhead.com/npc=18992/captain-krosh#comments:id=154618

- [x] Captain Krosh (entry 18992) death should trigger emote: "Captain Krosh is exhausted."

- [x] Ango'rosh Brute (entry 18119) uses Knockdown (ID 11428) a little too often (opinion). 2 sec stun with a 5 second CD, not a lot of room to damage him. 

- [x] Ango'rosh Ogre (entry 18117) uses Kick https://www.wowhead.com/spell=11978/kick every 5 seconds (locks school for 6 seconds) effectively rendering casters useless. Increase CD to 15-20?
https://www.wowhead.com/npc=18117/angorosh-ogre#abilities
https://www.wowhead.com/npc=18117/angorosh-ogre#comments:id=1121234

- [x] Ango'rosh Ogre (entry 18117) should sometimes say "You no take mushroom!" when aggroed
https://www.wowhead.com/npc=18117/angorosh-ogre#comments:id=182848:reply=40969

- [ ] Ango'rosh Ogre (entry 18117) should use a different axe when "mining" the mushrooms
![Image](https://i.gyazo.com/f4ffb5585097323774512c696e68c150.png)

- [x] Ango'rosh Shaman (entry 18188) Missing ability Bloodlust https://www.wowhead.com/spell=6742/bloodlust, Fire Nova Totem https://www.wowhead.com/npc=18118/angorosh-shaman#comments:id=1206398 One of these http://db.hellfire-tbc.com/?search=fire+nova+totem#spells ?
https://www.wowhead.com/npc=18118/angorosh-shaman#abilities

- [x] Ango'rosh Shaman (entry 18188) Only heals himself.

- [ ] Ango'rosh Shadowmage (GUID 72424, entry 20444) not patrolling

- [x] Ango'rosh Mauler (entry 18120) Not patrolling

GUID
64223
64230
64231
64232 (too many NPCs here?)
64242
64245

- [ ] Ango'rosh Souleater (entry 18121) Not patrolling

GUID
64246
64248

- [x] Ango'rosh Warlock (entry 19732) missing ability Summon Imp https://www.wowhead.com/spell=11939/summon-imp. Summons a Succubus instead with a level 30-40 loot table. Same problem as Feralfen hunter, does not act like a pet properly.
https://www.wowhead.com/npc=19732/angorosh-warlock#abilities

- [x] Looting https://www.wowhead.com/item=24240/box-of-mushrooms from object https://www.wowhead.com/object=182050/box-of-mushrooms should cause a Ango'rosh Mauler (entry 18120) to spawn. 
https://www.wowhead.com/object=182050/box-of-mushrooms#comments:id=133356

- [ ] Overlord Gorefirst (entry 18160) dual wield animation instead of 2h.
video: https://i.gyazo.com/570d5b3c34eab696c0c0e7fc0a15cfee.mp4
https://www.wowhead.com/npc=18160/overlord-gorefist

- [x] Daggerfen Muckdweller's https://www.wowhead.com/npc=18115/daggerfen-muckdweller#comments Paralytic Poison (ID 35201) https://www.wowhead.com/spell=35201/paralytic-poison does not stun at the end of its duration. 

- [x] Daggerfen Muckdweller does not attempt to run away on low health as they should.
From retail: 
![Image](https://i.gyazo.com/8aee86af243270ed181957b33cd51eb6.png)

- [ ] Paralytic Poison (ID 35201) should be "on next attack" spell like heroic strike, hands glowing green when it's activated allowing you to stun the mob to interrupt it. Currently it's an instant cast.
https://www.wowhead.com/spell=35201/paralytic-poison
https://www.wowhead.com/npc=18115/daggerfen-muckdweller#comments:id=83386

- [x] Daggerfen Assasain (Entry 18116)missing ability: Sneak (ID 22766)
https://www.wowhead.com/spell=22766/sneak
https://www.wowhead.com/npc=18116/daggerfen-assassin#abilities

- [x] Daggerfen Servant broken ability: Bandage https://www.wowhead.com/spell=35207/bandage, does not heal at all and does not apply aura 'recently bandaged' https://www.wowhead.com/spell=11196/recently-bandaged. Also they never attempt to heal Chieftain Mummaki.
https://www.wowhead.com/npc=19733/daggerfen-servant#comments
https://www.wowhead.com/npc=19174/chieftain-mummaki#comments:id=230275

- [ ] Chieftain Mummaki (entry 19174) uses Vanish https://www.wowhead.com/spell=35205/vanish in the fight as he should, but when he returns he just appears in front of you instead of using Backstab https://www.wowhead.com/spell=7159/backstab. 
https://www.wowhead.com/npc=19174/chieftain-mummaki
https://www.wowhead.com/npc=19174/chieftain-mummaki#abilities

- [x] Chieftain Mummaki (entry 19174) missing ability Wound Poison (probably one of these: http://db.hellfire-tbc.com/?spell=36974 or http://db.hellfire-tbc.com/?spell=30984) and Bandage https://www.wowhead.com/spell=35207/bandage which applies aura 'recently bandaged' https://www.wowhead.com/spell=11196/recently-bandaged
![Image](https://i.gyazo.com/7a810c02a0d4742140407f4c947c2865.jpg)
https://www.wowhead.com/npc=19174/chieftain-mummaki#comments:id=249642
https://www.wowhead.com/npc=19174/chieftain-mummaki#comments:id=61105

- [ ] Chieftain Mummaki has weird pathing and will sometimes go up on the roof if you try to move him back a little. 

- [x] Items "Mushroom Sample" (ID 24238) for quest https://www.wowhead.com/quest=9708/familiar-fungi seems to be 100%, wowhead and comments suggest that it's more around 30-50% drop rate.
https://www.wowhead.com/item=24238/mushroom-sample#comments

- [x] Mudfin Frenzy (entry 18212) only spawn at the bottom of the lake and stand still. They should be swimming around a bit in the water.

- [x] Fenclaw Thrasher (entry 18214) does not move around, stands still at the bottom of the lake.

- [x]  Fhwoor Smash! (quest ID 9729) escort quest does not start. NPC: Fhwoor (entry 17877)

- [x] Watcher Leesa'oh (entry 17271) should be standing still, walks around a lot.

- [x] Missing event upon handing in quest "Stealing Back the Mushrooms" (ID 9709) 
http://wowwiki.wikia.com/wiki/Watcher_Leesa%27oh
http://wowwiki.wikia.com/wiki/Quest:Stealing_Back_the_Mushrooms
https://www.wowhead.com/quest=9709/stealing-back-the-mushrooms

Video of event: https://youtu.be/zRX9swr55Zs?t=6m44s

- [x] Terrowclaw missing ability Fear https://www.wowhead.com/spell=34259/fear 
https://www.wowhead.com/npc=20477/terrorclaw#abilities

- [ ] Bogstrok missing around Terrorclaw near these cords: ![Image](https://i.gyazo.com/209d4c17e8243aa24b2a9f8d49a1dda1.png)
https://www.wowhead.com/npc=20477/terrorclaw#comments:id=34276

https://www.wowhead.com/npc=20710/bogstrok-hatchling
https://www.wowhead.com/npc=20294/bogstrok-razorclaw
https://www.wowhead.com/npc=20295/bogstrok-crusher
https://www.wowhead.com/npc=20293/bogstrok-clacker

- [ ] Nagas missing around these cords: ![Image](https://i.gyazo.com/2a37e2963d5acc33406e7d1a9bc192c8.png)
https://www.wowhead.com/npc=18089/bloodscale-slavedriver
https://www.wowhead.com/npc=18088/bloodscale-enchantress

- [x] Telredor Guard (entry 18922) missing ability Shield Block https://www.wowhead.com/spell=12169/shield-block

- [x] Telredor Guard (entry 18922) very low damage wowhead states 1k damage on cloth, currently ~300 damage on a naked target. 
https://www.wowhead.com/npc=18922/telredor-guard#comments:id=369869

- [x] Telredor Guard (entry 18922) and Orebor Harborage Defender (entry 18943) Wrong attack animation, uses fists instead of weapons.

- [ ] Telredor Guard (GUID 67942/67942, entry 18922) desync patrol 
![Image](https://i.gyazo.com/258bb4d7334175aacf29a2e0b0b44437.png)

- [x] Orebor Harborage Defender (entry 18943) missing abilities Shield Block https://www.wowhead.com/spell=12169/shield-block, Revenge https://www.wowhead.com/spell=12170/revenge
Same damage as Telredor Guard, buff?
https://www.wowhead.com/npc=18943/orebor-harborage-defender

- [x] Swamprat Guard (GUID 67907, entry 18910) not linked to her patrolling buddy, standing still.

- [ ] Expedition Warden (entry 17855) missing exalted say. "If you are exalted with Cenarion Expedition, the two night elves at the entrance of the Cenarion Refuge inn, will salute you when you walk past them. The female night elf will even show how delighted she is to see you, saying either: 'You honor us with your presence, <name>.' or 'Welcome back <name>.'"
https://www.wowhead.com/npc=17855/expedition-warden#comments:id=1926188

- [ ] Expedition Warden (entry 17855) spawn missing, cords: ![Image](https://i.gyazo.com/a6aaf2f30190bb3cdbf664ce7774e2e7.png) screenshot: ![Image](https://i.gyazo.com/e1efbcee01e2e6573b7126431d6b64fc.jpg)

- [ ] Expedition Flare (item ID 24429) does currently not summon an Expedition Scout (entry 18126). 
- The Scout should stay for 30 seconds or however long combat lasts. 
- Will attack other players of the opposite faction. 
- Will automatically attack anything hostile nearby when summoned, even other players.
- Scales with gear/level (same scaling as shaman elemental totems?). 
- Their damage seems to start at 150 per hit in bad gear, some players reported hit upwards of 300 (can also crit)
- Runs faster than players
- Says "My work here is done." when despawning.

https://www.wowhead.com/item=24429/expedition-flare#comments
https://www.wowhead.com/npc=18126/expedition-scout

- [x] Mal'druk the Soulrender (entry 20445) 
- Upon pull he should say "I'll crush you!".
- Should banish himself when he summons shades of himself. 
- Should spawn 2 shades, currently just 1.
- The shade is currently friendly to both alliance and horde.
- Sometimes he interrupts his Mind Flay to melee attack instead.
- The shade summoned is missing his staff.
- Hits weak, increase damage by about 25%
- Should do this emote when he banishes himself: "Mal'druk the Soulrender departs from the world and summons shades to do his bidding."

Summoning spell: http://db.hellfire-tbc.com/?spell=35425
Mind Flay: http://db.hellfire-tbc.com/?spell=16568
Shade: http://db.hellfire-tbc.com/?npc=20669

http://i.imgur.com/hcH3JOk.jpg
https://www.wowhead.com/npc=20445/maldruk-the-soulrender#comments

- [ ] Burstcap Murshroom (object 182095) can't be interacted with when you have the quest Burstcap Mushrooms, Mon! (quest 9814). "You can't open that." error.

- [ ] Zabra'jin Guard (GUID 67883, entry 18909) facing the wrong way when at end of patrol.
![Image](https://i.gyazo.com/2f69839ba2636ae6dd76c582cba3058d.png)

He also desyncs with his buddy (GUID 67884)
![Image](https://i.gyazo.com/08e61ddcb4e35c5b53904a27510c42ca.png)

- [ ] Zabra'jin Guard (GUID 67905, entry 18909) 
facing the wrong way when at end of patrol.
![Image](https://i.gyazo.com/313f7f17d32de82a8e5c8f6baba77a7e.png)

desync patrol with his buddy GUID 67904
![Image](https://i.gyazo.com/8bcafef72e7339007bcf308bc4c5c75f.png)

- [ ] Zabra'jin Guard (GUID 67892/67889/67901, entry 18909) all patrol alone and have weird patrols. Needs to be looked over.

- [x] Guard Untula (GUID 67112, entry 19380) should sometimes kick the gnome next to her, making him cry. 
Has 2 random /say: 
If you're no good at fixing, we'll see if you're good for eating. Now work!
Hurry up with that axe, you! I want it sharp enough to cut the wind!

https://www.wowhead.com/npc=19380/guard-untula#comments:id=133766
https://wow.gamepedia.com/Guard_Untula

- [x] Guard Untula (GUID 67112, entry 19380) is currently a male, should have female model.

- [ ]  When summoning Feralfen Serpent Spirit (18185) using Feralfen Totem (item 24498) you should place a totem on the ground as seen here:
![Image](https://i.gyazo.com/78322b4cb1ac13fcc642ddde829aba27.png)
Currently there's no totem.

- [ ] Ango'rosh Attack Plans (object 182166) "You can't open that." error.

- [ ] Have You Ever Seen One of These? (quest 9816) takes forever for the quest to show up as complete. Should instantly complete when you use the item to release the murlocs. Shows up as completed multiple times on the screen.

- [x] Alliance players are able to pick up WANTED: Boss Grog'ak (quest 9820) and Wanted: Chieftain Mummaki (quest 10117) from the wanted poster in Zabra'jin

- [x] Fulgore Spore (object 182116) is very rare. Only 3 spawns in game and you need 6 to complete the quest. Should have ~25 spawn locations.
Sunwell:
![Image](https://i.gyazo.com/f5014c15430702c07b13d4afbaf52dae.png)
Retail:
![Image](https://i.gyazo.com/5026ee5f7cfa9d8db4900e3dd507a92b.png)

http://db.hellfire-tbc.com/?object=182116
Map of their retail locations: https://www.wowhead.com/object=182116/fulgor-spore#comments

- [ ] Elder Kuruti (entry 18197) should have a speech bubble on mouseover when you're friendly with him.

### **Twin Spire Ruins**

- [ ] Zangarmarsh PvP Beam (Red) (GUID 84756, entry 18757) infernal is always visable. 
![Image](https://i.gyazo.com/4193f4345677dffc30e705e3c9fbf9b6.png)

- [ ] Zangarmarsh PvP Beam (Blue) is visable in both towers and the GY when they are neutral, and keeps moving around like it's a mob. The western one is also inside the building, not on top.

- [ ] The beam does not change colour when a faction captures the tower.

- [ ] The central graveyard has the alliance flag there by default.
![Image](https://i.gyazo.com/2c3f0c6104ac0e5a22ec88baaaa9ccba.png)

- [ ] You cannot place a flag at the center GY after you've captured both towers.

http://wowwiki.wikia.com/wiki/Mark_of_Thrallmar
https://wow.gamepedia.com/Twin_Spire_Ruins
http://wowwiki.wikia.com/wiki/Twin_Spire_Ruins
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2083
https://www.wowhead.com/spell=33779/twin-spire-blessing#comments

**Comment by Silroth** [comment]
- Xeleth doesnt use any of his abilities, should use Focused Bursts (Spell ID 36414) and Tongue Lash (Spell ID 36398)

**Comment by Dootz** [comment]
@Riztazz many patroling issues were resolved be last tbc path update.

**Comment by notsofamous** [comment]
- [ ]     Dreghood Drudge (entry 18122) and Wrekt Slave (entry 18123) still not using Shared Bonds (Should only be cast **instantly** on other slaves when pulled)
    http://db.hellfire-tbc.com/?spell=34788
    http://db.hellfire-tbc.com/?spell=34789
    https://www.wowhead.com/npc=18122/dreghood-drudge#abilities
    https://www.wowhead.com/npc=19946/darkcrest-slaver#comments:id=352039

Shared Bonds being used: https://youtu.be/c-VoYkESb-U?t=13s

**Comment by sadfx** [comment]
Wrekt Slaves still broken af

**Comment by blackabbath** [comment]
confirm Expedition Flare doesn't summon Cenarion Expedition unit to my aid.
