### ISSUE TITLE
Quest:  Kodo Roundup - Kodos are already tamed

### ISSUE THREAD

**Issue by Offroads** [SunwellWoW/Sunwell-TBC-Bugtracker#2893]
Description: The quest Kodo Roundup in Desolace is broken. All the kodos walking around are friendly with the name Tamed Kodo.

How it works: All kodos are friendly and named Tamed Kodo

How it should work: There should be Ancient, Aged or Dying Kodo walking around.

![wowscrnshot_120818_233333](https://user-images.githubusercontent.com/28876369/49691416-ffed7c00-fb41-11e8-8948-e645a161f6ea.jpg)

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.

**Comment by Offroads** [comment]
![image](https://user-images.githubusercontent.com/28876369/50425419-dd639e80-0875-11e9-9ed6-db178479ea03.png)
Still broken btw.
