### ISSUE TITLE
Shaman : Grounding Totem

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#663]
Decription: Grounding Totem, read the tooltip : https://tbc-twinhead.twinstar.cz/?spell=8177

How it works : It does not, as you can see here : https://imgur.com/a/Af39ikq

How it should work : It should redirect the next harmful spell casted on the shaman or a party member on itself, destroying the totem. As the tooltip says.
I think it's working the same way spell reflection (from Warrior's abilities) is working.

Source (you should point out proofs of your report, please give us some source): 
The tooltip.

**Comment by akrom23** [comment]
I can't see anything.

**Comment by Jeansapin** [comment]
Fixed : https://imgur.com/a/Af39ikq

**Comment by TP-Caitlin** [comment]
Still doesn't work currently. It doesn't apply the "Grounding Totem" buff to the shaman or anyone in the party.

**Comment by Kokaina** [comment]
If spell is reflected (e.g by warrior's Spell Reflection) it goes back directly to shaman as well, even if Grounding Totem is up.

**Comment by FrauHolle86** [comment]
Tested today:

- Grounding Totem gives the buff to the shaman and is redirecting the harmfull spells (OK)
- BUT Grounding Totem is not getting destroyed after (needs to be resolved)
- after a few seconds, the grounding buff on the shaman will just refresh because of that (needs to be resolved)

**Comment by zapsuu** [comment]
FrauHolle86 has right. If totem doesn't get direct dmg (for example Shadow Word: Pain) the Grounding Totem buff dissapper for few seconds and buff shaman again.

**Comment by Wojtyas** [comment]
Fixed & implemented (only SSC realm for now).
